# Generated by Django 6.0.6 on 2026-07-06 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnittingProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_project', models.CharField(max_length=50)),
                ('stitches', models.IntegerField()),
                ('needles', models.JSONField(default=dict)),
                ('yarn', models.JSONField(default=dict)),
                ('progress_grid', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True, default='')),
                ('row_notes', models.JSONField(blank=True, default=list)),
                ('completed', models.BooleanField(verbose_name=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knitting_project', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
