# Generated by Django 6.0.6 on 2026-07-06 20:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knitTracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnittingProject',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_of_project', models.CharField(max_length=255)),
                ('stitches', models.PositiveIntegerField()),
                ('needles', models.JSONField(blank=True, default=dict)),
                ('yarn', models.JSONField(blank=True, default=dict)),
                ('progress_grid', models.JSONField(blank=True, default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('row_notes', models.JSONField(blank=True, default=list)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knitting_projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='KnittingProjects',
        ),
    ]
