# Generated by Django 6.0.6 on 2026-07-23 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knitTracker', '0002_knittingproject_delete_knittingprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='knittingproject',
            name='autofill',
            field=models.TextField(blank=True, default=''),
        ),
    ]
